apiVersion: v1
kind: Service
metadata:
  name: data-ingestion-service
  namespace: investorcenter
  labels:
    app: data-ingestion-service
spec:
  type: ClusterIP
  selector:
    app: data-ingestion-service
  ports:
  - port: 8002
    targetPort: 8002
    protocol: TCP
